
on:
# მითიტებული მოდული გვეხმარება რომელ ბრანჩზე უნდა გაეშვას მითითებული pipeline
  workflow_dispatch:
    inputs:
      environment:
        type: environment
        description: select the environment
        default: test
      boolean:
        type: boolean
        description: with or without test
        default: true
      someoptions:
        type: choice
        description: select version
        options:
          - "1.1"
          - "2.2"
          - "3.3"


  push:
    branches: [ main ]


jobs:
  test_job:
    name: testjob
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone 
        uses: actions/checkout@v2
        
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'


      - name: test our shell script
        run: |
          pip install pandas
          pip install setuptools
          echo ${{ inputs.someoptions.options}}
          mkdir test123
          ls
          cd test123
          ls 
          pwd
